version: '3.9'

services:
  database:
    container_name: database
    build: 
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library

  server-api:
    container_name: server-api
    build: 
      context: .
      dockerfile: Dockerfile
      target: server-api
    depends_on:
      - database
    ports:
      - 9000:9000
    environment:
      - NODE_ENV=1
      - DB_HOST=database
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB=library
      - PORT=9000

  client-ui:
    container_name: client-ui
    build: 
      context: .
      dockerfile: Dockerfile
      target: client-ui
    depends_on:
      - server-api
    ports:
      - 8081:80