export const auth = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL'
}

export const error = {
    GET_ERRORS: 'GET_ERRORS',
    CLEAR_ERRORS: 'CLEAR_ERRORS'
}

export const book = {
    GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
    GET_BOOKS_FAIL: 'GET_BOOKS_FAIL',
    SEARCH_BOOKS_SUCCESS: 'SEARCH_BOOKS_SUCCESS',
    SEARCH_BOOKS_FAIL: 'SEARCH_BOOKS_FAIL',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
    GET_BOOK_FAIL: 'GET_BOOK_FAIL',
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAIL: 'CREATE_BOOK_FAIL',
    UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',
    UPDATE_BOOK_FAIL: 'UPDATE_BOOK_FAIL',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAIL: 'DELETE_BOOK_FAIL'
}

export const copy = {
    GET_COPIES_SUCCESS: 'GET_COPIES_SUCCESS',
    GET_COPIES_FAIL: 'GET_COPIES_FAIL',
    CREATE_COPY_SUCCESS: 'CREATE_COPY_SUCCESS',
    CREATE_COPY_FAIL: 'CREATE_COPY_FAIL',
    UPDATE_COPY_SUCCESS: 'UPDATE_COPY_SUCCESS',
    UPDATE_COPY_FAIL: 'UPDATE_COPY_FAIL',
    DELETE_COPY_SUCCESS: 'DELETE_COPY_SUCCESS',
    DELETE_COPY_FAIL: 'DELETE_COPY_FAIL'
}

export const borrower = {
    GET_BORROWERS_SUCCESS: 'GET_BORROWERS_SUCCESS',
    GET_BORROWERS_FAIL: 'GET_BORROWERS_FAIL',
    GET_BORROWER_SUCCESS: 'GET_BORROWER_SUCCESS',
    GET_BORROWER_FAIL: 'GET_BORROWER_FAIL',
    SEARCH_BORROWERS_SUCCESS: 'SEARCH_BORROWERS_SUCCESS',
    SEARCH_BORROWERS_FAIL: 'SEARCH_BORROWERS_FAIL',
    DELETE_BORROWER_SUCCESS: 'DELETE_BORROWER_SUCCESS',
    DELETE_BORROWER_FAIL: 'DELETE_BORROWER_FAIL'
}

export const loan = {
    GET_LOANS_SUCCESS: 'GET_LOANS_SUCCESS',
    GET_LOANS_FAIL: 'GET_LOANS_FAIL',
    CREATE_LOAN_SUCCESS: 'CREATE_LOAN_SUCCESS',
    CREATE_LOAN_FAIL: 'CREATE_LOAN_FAIL',
    UPDATE_LOAN_SUCCESS: 'UPDATE_LOAN_SUCCESS',
    UPDATE_LOAN_FAIL: 'UPDATE_LOAN_FAIL',
    DELETE_LOAN_SUCCESS: 'DELETE_LOAN_SUCCESS',
    DELETE_LOAN_FAIL: 'DELETE_LOAN_FAIL'
}